export const initialCheckers = [
  {
    id: 1,
    name: "Sarah Johnson",
    profileImage: "/img/checker/5.png",
    rating: 4.9,
    reviews: 127,
    experience: "5 years",
    specialties: ["Hotels", "Luxury Resorts", "Boutique Properties"],
    location: { country: "Spain", city: "Barcelona", region: "Catalonia" },
    coverageArea: "Barcelona Metropolitan Area",
    languages: ["English", "Spanish", "French"],
    price: 45,
    responseTime: "Within 2 hours",
    description: "Expert accommodation checker specializing in luxury hotels and unique properties in Barcelona.",
    verified: true,
    completedChecks: 340
  },
  {
    id: 2,
    name: "Marcus Williams",
    profileImage: "/img/checker/6.png",
    rating: 4.8,
    reviews: 89,
    experience: "3 years",
    specialties: ["Budget Hotels", "Hostels", "Apartments"],
    location: { country: "Spain", city: "Madrid", region: "Madrid" },
    coverageArea: "Madrid City Center",
    languages: ["English", "Spanish"],
    price: 35,
    responseTime: "Within 1 hour",
    description: "Reliable checker focused on budget-friendly accommodations and student housing.",
    verified: true,
    completedChecks: 256
  },
  {
    id: 3,
    name: "David Chen",
    profileImage: "/img/checker/3.png",
    rating: 4.7,
    reviews: 156,
    experience: "4 years",
    specialties: ["Business Hotels", "Conference Centers", "Corporate Housing"],
    location: { country: "France", city: "Paris", region: "Île-de-France" },
    coverageArea: "Greater Paris Area",
    languages: ["English", "French", "Mandarin"],
    price: 55,
    responseTime: "Within 3 hours",
    description: "Professional checker with expertise in business accommodations and corporate travel.",
    verified: true,
    completedChecks: 423
  },
  {
    id: 4,
    name: "Isabella Rodriguez",
    profileImage: "/img/checker/4.png",
    rating: 4.9,
    reviews: 203,
    experience: "6 years",
    specialties: ["Restaurants", "Fine Dining", "Local Cuisine"],
    location: { country: "Italy", city: "Rome", region: "Lazio" },
    coverageArea: "Rome Historic Center",
    languages: ["English", "Italian", "Spanish"],
    price: 40,
    responseTime: "Within 1 hour",
    description: "Food and dining expert specializing in authentic Italian restaurants and culinary experiences.",
    verified: true,
    completedChecks: 567
  }
];
interface MapGeoName {
  [country: string]: string[];
}

const data: MapGeoName = {
  "United States": ["New York", "Los Angeles", "Chicago", "Miami", "Houston", "Seattle", "Boston", "San Francisco"],
  "France": ["Paris", "Lyon", "Marseille", "Nice", "Toulouse", "Bordeaux", "Strasbourg"],
  "Germany": ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf"],
  "Japan": ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo", "Fukuoka"],
  "Brazil": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador", "Fortaleza", "Recife", "Manaus"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Ahmedabad", "Pune"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Xi'an", "Chongqing"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Liverpool", "Bristol"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Quebec City"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Samara", "Rostov-on-Don"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Florence", "Venice", "Bologna"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Mérida"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Hurghada"],
  "Nigeria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán"],
  "Thailand": ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi", "Chiang Rai"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar"],
  "Pakistan": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi", "Multan"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho"],
  "Philippines": ["Manila", "Davao City", "Cebu City", "Quezon City", "Zamboanga City"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  "Morocco": ["Casablanca", "Marrakech", "Rabat", "Fez", "Tangier"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Penang", "Kota Kinabalu"],
  "Peru": ["Lima", "Arequipa", "Cusco", "Trujillo", "Chiclayo"],
  "Ukraine": ["Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "Poland": ["Warsaw", "Kraków", "Wrocław", "Pozព", "Gdańsk", "Łódź"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Tabriz", "Shiraz"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Singapore": ["Singapore", "Jurong", "Woodlands", "Tampines", "Pasir Ris"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi"],
  "Ireland": ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  "Portugal": ["Lisbon", "Porto", "Faro", "Coimbra", "Braga"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Adama", "Hawassa"]
};

export default data;